name: Call Reusable workflow

on:
  push:
    branches:
      - main  # or 'master' depending on your default branch name
  workflow_dispatch: # optional: lets you trigger it manually from the GitHub UI

jobs:
  call-greeting:
    uses: ./.github/workflows/resuable.yml